pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
				rootDir: "WebbApp/quickstart/"
				sh './gradlew clean build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}