pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
				dir ('WebbApp/quickstart/') {
					sh 'pwd'
				}
				sh './gradlew clean build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}